### ISSUE TITLE
[Suggestion] Setting Explanation

### ISSUE THREAD

**Issue by ardissaps** [quiqueck/BCLib#1]
### Description

So we have an ide what it is on True or False

**Comment by paulevsGitch** [comment]
All values have almost good names, so you will be able to know what any option does only knowing its name. Also JSON format don't provide any comments

**Comment by ardissaps** [comment]
> All values have almost good names, so you will be able to know what any option does only knowing its name. Also JSON format don't provide any comments

I see, thank you.

Addition : How about to add option to "not backup" while auto applying patch when loading world? (so no need backup confirmation, just load the world and auto patch without question prompt) Thanks in advance

**Comment by quiqueck** [comment]
I am assuming to run on 1.18.2, as it has an issue with Datapack loading order which results in a constant nag about patching the world.

In that case, it might actaually be a good addition for 1.18.2. However, from 1.19 onward, the patch screen should not come up as often as it does in 1.18.2.
