### ISSUE TITLE
[Bug] WunderLibPath is ignored. Searches for remote repositories

### ISSUE THREAD

**Issue by joser93** [quiqueck/BCLib#100]
Steps to reproduce:

1. Clone and build WunderLib 1.20 https://github.com/quiqueck/WunderLib/tree/1.20
2. Clone and build BCLib 1.20

Expected behavior: 
WunderLibPath should be use and detects the path for the project

Current behavior: 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'BCLib'.
> Could not resolve all dependencies for configuration ':modApi'.
   > Could not find com.github.quiqueck:WunderLib:1.1.0.
     Searched in the following locations:
       - file:/home/joser93/MinecraftMods/BCLib/.gradle/loom-cache/remapped_mods/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://maven.fabricmc.net/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://libraries.minecraft.net/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://libraries.minecraft.net/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.jar
       - https://repo.maven.apache.org/maven2/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - file:/home/joser93/.gradle/caches/fabric-loom/1.1.0/WunderLib.jar
       - file:/home/joser93/MinecraftMods/BCLib/.gradle/loom-cache/1.1.0/WunderLib.jar
       - https://maven.dblsaiko.net/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://maven.shedaniel.me/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://maven.blamejared.com/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://jitpack.io/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://maven.terraformersmc.com/releases/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
       - https://maven.terraformersmc.com/com/github/quiqueck/WunderLib/1.1.0/WunderLib-1.1.0.pom
     Required by:
         project :

```

I am aware that the current settings.gradle detects the directory into '../Wunderlib' and currently I have it setup like that, even tried to change it to the absolute path to the project and isn't capable to detect it.

**Comment by StonksMan001** [comment]
you have to download WunderLib from github (https://github.com/quiqueck/WunderLib/tree/1.20) then run ./gradlew genSources idea (or eclipse) in the terminal, after that ./graldew build, then go into build/libs, and search for the wunderlib.jar file, then you have to rename it to exactly "WunderLib.jar", and copy it. Then go back to bclib and paste the copied file to your .gralde/loom-cache/(make new folder if nesecarry)1.1.0 folder. after that run ./gradlew genSources again and you should be fine

**Comment by quiqueck** [comment]
Have a look at this line:
https://github.com/quiqueck/BCLib/blob/d1a4e6c13d37a608e8dd6bad3f2f2164a1fa884f/settings.gradle#L20

When you reload the gradle file, IntelliJ will pick up a local installation WunderLib when the cloned repo is found at the given path.

If you compile from a commandLine you will also need to enable this:
https://github.com/quiqueck/BCLib/blob/d1a4e6c13d37a608e8dd6bad3f2f2164a1fa884f/settings.gradle#L17
