### ISSUE TITLE
[Bug] Getting this Crash with BClib when using Biolith 

### ISSUE THREAD

**Issue by Daihok41** [quiqueck/BCLib#101]
### What happened?

As soon as it trys to load world it saves and crashs. This is just with bclib without better nether or better end.  https://pastebin.com/rVTeBT49

### BCLib

3.0.7

### Fabric API

0.83.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
https://pastebin.com/rVTeBT49
```

### Other Mods

```shell
List of mods is in crash log
```

**Comment by quiqueck** [comment]
This is a duplicate of TerraformersMC/Biolith#4 and quiqueck/BetterNether#138.

**Comment by Daihok41** [comment]
Yea except im not using Biolith lol
