### ISSUE TITLE
[Suggestion] I think there should be 32x Resolution option for BetterX textures.

### ISSUE THREAD

**Issue by DiePutin3782** [quiqueck/BCLib#12]
### Description

There should be a toggle option, or resource pack that makes every block, mob, item, ETC in Betterend, Betternether, and Eden Ring have 32x resolution. This would plug into the 32x faithful texture pack for anybody who uses that. People can get this BetterX 32x resolution texture pack to get the 32x textures for the BetterX mods, so that if somebody uses 32x Faithful pack, the better end, better nether, and eden ring mods would fit in with 32x faithful a LOT better.

**Comment by quiqueck** [comment]
That would be nice :D 
If there are artists around that would like to update the textures, we are happy to include them :)

However, I currently do not have the time to create higher res textures.
