### ISSUE TITLE
[Bug] mismatch

### ISSUE THREAD

**Issue by Rogenar** [quiqueck/BCLib#120]
### What happened?

A bug happened!
![ss1](https://github.com/quiqueck/BCLib/assets/122460325/f84fcfbd-1d3b-425e-a958-e2f5fa73cb51)

### BCLib

3.0.12

### Fabric API

0.86.0

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
.
```

### Other Mods

```shell
better-nether-9.0.9
better-end-4.0.9
```

**Comment by lospejos** [comment]
Have the same issue.

From `fabric.mod.json` I see:

```
"breaks": {
    ...
    "fabric": "\u003e\u003d0.86"
  }
```

I suppose that this is the cause of this error. But question is was it added intentionally or not? And if it was, what is broken when using `BCLib 3.0.12` with `Fabric API 0.86.0`.

Previous mod version `BCLib 3.0.11` runs well with `Fabric API 0.86.0`.

**Comment by lospejos** [comment]
As a workaround in file `fabric.mod.json` inside archive `bclib-3.0.12.jar` I removed line:

```
"fabric": "\u003e\u003d0.86"
```

in `breaks` section.

Successfully ran using updated `bclib-3.0.12.jar`, `better-end-4.0.9.jar` and `better-nether-9.0.9.jar`.

**Comment by Rogenar** [comment]
I can't do that right now because there are too many mods. I will wait for an edited version

**Comment by LokeYourC3PH** [comment]
+1

**Comment by nvb-uy** [comment]
bump

**Comment by LokeYourC3PH** [comment]
Seems like more than just BCLib is fucked up. Mods like BetterEnd crash now upon generating new chunks. Rushed release, I guess? I will rollback BCLib and the BetterEnd/Nether mods.

**Comment by nvb-uy** [comment]
I can't use mods that rely on the latest fabric api version if the betterx mods are present due to this. If I try using the latest version, it doesn't load, and if I try using an older version, the newer mods that depend solely on the latest fapi version won't load either. This issue needs to be fixed asap because it's breaking modpacks completely, basically leaving only 2 options: to not add new mods, or to remove all betterx mods completely

**Comment by paulevsGitch** [comment]
You need to use Fabric API 0.85, not 0.86 or newer. This is what message mean.

> I suppose that this is the cause of this error. But question is was it added intentionally or not

Yes, it is intentional. BCLib don't work with 0.86

**Comment by Rogenar** [comment]
fabric api 0.86.1 is out
