### ISSUE TITLE
[Bug] BCLib incompatible with Fabric API 0.86.x

### ISSUE THREAD

**Issue by PHTMDiRoNo** [quiqueck/BCLib#122]
### What happened?

I saw on a different page that this was mentioned but was closed and marked complete. I don't know if that meant that it was fixed or whatever, so I figured I should probably write a new bug report just in case, because I am still getting the error with the latest version of BCLib.

### BCLib

3.0.12

### Fabric API

0.86.x

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'BCLib' (bclib) 3.0.12 with any version that is compatible with:
		 - Other constraints that can''t be automatically determined
Unmet dependency listing:
	 - Mod 'BCLib' (bclib) 3.0.12 is incompatible with version 0.86 or later of mod 'Fabric API' (fabric-api), but a matching version is present: 0.86.1+1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by MbtMarco** [comment]
He knows that. Hes working to fix that.

**Comment by Gamemassa** [comment]
I saw in the changelog for 3.0.13 that was just released today, that support was added for Fabric API 0.86.x, but when I upgraded BCLib to 3.0.13, it's still telling me it's not compatible.

![image](https://github.com/quiqueck/BCLib/assets/18667108/db1e527d-7027-4019-942b-ef6a741d25ab)

**Comment by PHTMDiRoNo** [comment]
I think 3.0.13 is porbably only compatible with 0.86.1.

**Comment by MbtMarco** [comment]
If u are on Quilt there isnt a Fabric Api 0.86.1 and latest version of bclib works only on 0.86.1

**Comment by MbtMarco** [comment]
> I saw in the changelog for 3.0.13 that was just released today, that support was added for Fabric API 0.86.x, but when I upgraded BCLib to 3.0.13, it's still telling me it's not compatible.
> 
> ![image](https://github.com/quiqueck/BCLib/assets/18667108/db1e527d-7027-4019-942b-ef6a741d25ab)
> 

If u are on Quilt there isnt a Fabric Api 0.86.1 and latest version of bclib works only on 0.86.1

**Comment by temyy** [comment]
> If u are on Quilt there isnt a Fabric Api 0.86.1 and latest version of bclib works only on 0.86.1

yes there is https://modrinth.com/mod/qsl/version/7.1.0+0.86.1-1.20.1

**Comment by MbtMarco** [comment]
> yes there is https://modrinth.com/mod/qsl/version/7.1.0+0.86.1-1.20.1

Didnt see it

**Comment by Gamemassa** [comment]
I'm on Fabric, but I didn't realize there was a newer version.

Edit: updating to Fabric 0.86.1 fixed my issue. Thanks guys!
