### ISSUE TITLE
[Bug] [1.20.1] BetterX worldtype breaks other mod's

### ISSUE THREAD

**Issue by Cixon** [quiqueck/BCLib#129]
### What happened?

Cinderscapes, Regions Unexplored and Biome-replacer all fall victim to BCLib's BetterX worldtype despite not having BetterNether or any nether affiliated mod installed.

Attempts were made to disable settings but nothing worked. See ticket:
https://github.com/WerDei/Biome-Replacer/issues/2

### BCLib

3.0.13

### Fabric API

0.88.1

### Fabric Loader

0.14.22

### Minecraft

1.20.1

### Relevant log output

```shell
n/a
```

### Other Mods

```shell
https://www.curseforge.com/minecraft/mc-mods/biome-replacer

https://www.curseforge.com/minecraft/mc-mods/cinderscapes

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored/files/4721508
```

**Comment by Cixon** [comment]
Didn’t explain lol. “Fall Victim” meaning their configurations do not work. Like disabling a biome to generate in the Nether through their config, changes nothing and with Biome replacer’s case - that mod is unable to change any biome with BCLib present.

**Comment by Cixon** [comment]
Found out why, it’s the Better X preset. The worldtype needs a patch.

**Comment by quiqueck** [comment]
We simply pick up every Nether Biome that is available and auto add it (we do not read the config files of other mods). If you want to disable Biomes from other mods, you can add them to the exclusion lists in **config/bclib/biomes.json**. Just add the Biome ID to the `NETHER` in `force_exclude`:

```json
{
  "force_include": {
    "NETHER": [],
    "END_LAND": [],
    "END_VOID": [],
    "END_CENTER": [],
    "END_BARRENS": []
  },
  "force_exclude": {
    "NETHER": ["betternether:nether_waste"],
    "END": []
  }
}
```
