### ISSUE TITLE
[Bug] End biomes generating in incorrect locations

### ISSUE THREAD

**Issue by lunarbunten** [quiqueck/BCLib#13]
### What happened?

Using the latest version of BCLib in 1.19, end biomes continue to generate in incorrect locations.

"end_highlands, "end_midlands", and often times "end_barrens" biomes generate independently of location to islands.
The center islands "the_end" biome generates in the outer regions of the end (1000+ blocks out) despite the fact it should never generate there usually.

With the latest update of BCLib, islands biomes now generate where land should be despite the fact this should not happen, and the reverse happens for land biomes generating spaces where islands should be.

The result of this causes The End becoming overly barren and looking very different from how it should with vanilla generation.

### With BCLib

![2022-07-01_10 38 14](https://user-images.githubusercontent.com/35529203/176926298-a75c1cb1-2401-4491-8e40-df84aa16a18a.png)
![2022-07-01_10 38 26](https://user-images.githubusercontent.com/35529203/176926308-4755c4b5-d39a-438f-8d15-361f8b7f89e1.png)

### Without BCLib

![2022-07-01_10 40 26](https://user-images.githubusercontent.com/35529203/176926654-edb4c429-1349-4199-b920-1a30ea18cac1.png)
![2022-07-01_10 40 32](https://user-images.githubusercontent.com/35529203/176926660-07c6c625-9c86-4b6c-8431-cbc1de6c17d1.png)

I would appreciate if this issue was fixed, or at least remedied. My own mod, Enderscape, relies on BCLib, and these issues greatly hinder the experience.

### BCLib

2.0.7

### Fabric API

0.56.0

### Fabric Loader

0.14.6

### Minecraft

1.19

**Comment by quiqueck** [comment]
Are this biomes registered using BCLib, Datapack for Fabric?
Or is this in vanilla?

**Comment by lunarbunten** [comment]
The "With BCLib" examples I provided use BCLib with no other mods that affect world generation, so I would assume BCLib

**Comment by quiqueck** [comment]
Hm, might be the changes I implemented for Quilt. I will check...

**Comment by quiqueck** [comment]
Fixes released with 2.0.8
