### ISSUE TITLE
[Bug] Crash server

### ISSUE THREAD

**Issue by DonorKrovi** [quiqueck/BCLib#133]
### What happened?

[A bug happened!](https://github.com/RelativityMC/C2ME-fabric/issues/248)

### BCLib

3.0.13

### Fabric API

0.89.0

### Fabric Loader

idk 1.20.1

### Minecraft

1.20.1

**Comment by purejosh** [comment]
I don't understand how you think you'll get the dev to _want_ to fix this, with a useless report like this.

**Comment by quiqueck** [comment]
Should be fixed in the just released version (3.0.14)
