### ISSUE TITLE
[Bug] "@Environment(EnvType.CLIENT)" line in the code causes the server to crash (this goes for better end as well) on fabric 0.15+

### ISSUE THREAD

**Issue by xg787** [quiqueck/BCLib#138]
### What happened?

"@Environment(EnvType.CLIENT)" line in the code causes the server to crash (this goes for better end as well) on fabric 0.15+ and loads just fine without it in the code on server

### BCLib

any

### Fabric API

0.90.7

### Fabric Loader

0.15+

### Minecraft

1.20.1

**Comment by Mysterious-Wrangler** [comment]
Anyone figure out a work around or something? Im trying to start a server but this is holding me back and who knows when it will get fixed.
Edit: fixed one of the crashes by building the jar from a fork, but better end is still not working unfortunately.

**Comment by liehr** [comment]
Getting the same error here.

**Comment by Linguardium** [comment]
duplicate of #136 and #137

**Comment by quiqueck** [comment]
Duplicate of #136
