### ISSUE TITLE
[Suggestion] I think this should also allow any vanilla clients to join servers with ALL the BetterX mods on!

### ISSUE THREAD

**Issue by DiePutin3782** [quiqueck/BCLib#17]
### Description

My idea is that BClib allows a VANILLA client to join a server with these mods installed! BClib would communicate with the client and give it all the item ids, models, textures, ETC. This would make hosting a server with the BetterX mods a LOT easier! :D

**Comment by quiqueck** [comment]
Thanks for the nice idea, however at this point we do not intend to build a standalone version of BCLib that could provide the functionality.

**Comment by DiePutin3782** [comment]
It is still possible, it would require a lot of complex programming, and stuff... Maybe there could be a seperate mod that allows that sort of functionality???

**Comment by quiqueck** [comment]
It sure is possible, but not within the scope of our mods.
