### ISSUE TITLE
[Bug] Axes don't work 1.21

### ISSUE THREAD

**Issue by happykgit** [quiqueck/BCLib#175]
### What happened?

When BClib and World weaver (idk which one) downloaded, axes mine just like a hand

https://github.com/quiqueck/BCLib/assets/169473266/d28ccec7-c902-4415-970d-5343175c4166

### BCLib

21.0.0

### Fabric API

0.100.3

### Fabric Loader

0.15.11

### Minecraft

1.20.4

### Other Mods

```shell
World Weaver. WTHIT (client mod)
```

**Comment by quiqueck** [comment]
I think this was fixed in one of the latest updates
