### ISSUE TITLE
Game startup delays?

### ISSUE THREAD

**Issue by KateReller** [quiqueck/BCLib#18]
### What happened?

Minecraft takes an abnormal amount of time to start ranging from three to five minutes.

https://paste.ee/p/xm9x5#s=0&l=630

### BCLib

2.0.10

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment]
Thanks for reporting. May I ask why you attribute this delay to bclib?

**Comment by KateReller** [comment]
After more testing, it's not this mod _specifically._ The reason I thought it was this mod is because the delay stopped when this lib was disabled. But several other mods (Very Many Players, NoChatReport, etc.) also made the delay go away. And now it seems to be almost random because of the many mods I have installed.

**Comment by quiqueck** [comment]
Hm, might be a RAM issue? Have you tried to increase the memory assigned to your server?

**Comment by KateReller** [comment]
It's a client issue, surprisingly does not happen when launching the server. Client happily uses 9 GBs of ram and the server takes up 7-8 GBs.
