### ISSUE TITLE
[Bug] Issue with the config and the `Distant Horizons` mod (1.21)

### ISSUE THREAD

**Issue by mpustovoi** [quiqueck/BCLib#185]
I'm using the `Distant Horizons` mod, which pushes the vanilla fog much farther from the camera, up to the ends of the LODs.
However, `BCLib` overrides fog handling, which is why I have to completely disable these settings:
![image](https://github.com/quiqueck/BCLib/assets/92390626/474136a9-d574-4859-bc72-08193be53fbd)

However, there is no config file in the `config/bclib` folder. It's always an empty folder.
Therefore, after re-entering the game, the near fog appears again, forcing you to manually turn it off each time via `Mod Menu`.

Showcase of a problem in a new world:
![image](https://github.com/quiqueck/BCLib/assets/92390626/d923b991-6f1b-42f8-9f0d-0f84082b3dc2)

**BCLib** 21.0.5
**Fabric API** 0.100.4+1.21
**Fabric Loader** 0.15.11
**Minecraft** 1.21

Here are the [`logs`](https://mclo.gs/O7Dkx1Q).
It doesn't really matter what other mods are installed.

I can generally assume that this is a `Cloth Config` issue, but I'm still not sure, since other config files are edited and saved normally.

**Comment by tennomai** [comment]
Happens for me too

**Comment by Themodduck** [comment]
me too

**Comment by quiqueck** [comment]
Should be fixed with the latest version.
