### ISSUE TITLE
BCLib prevents Terralith biomes from spawning

### ISSUE THREAD

**Issue by vedranskarica** [quiqueck/BCLib#19]
### What happened?

BCLib prevents Terralith biomes from spawning, possibly from other worldgen datapacks as well.

No errors are logged, and terralith biomes appear in the /locate list, but no biome spawns, only vanilla ones. Other datapack features are unaffected (custom structures spawn, and changes to vanilla biomes are present). Happens with both terralith as a mod, and as a datapack.
During startup BCLib does report "Sorting features" in terralith biomes:

[bclib] Sorting Features in Biome: terralith:mountain_steppe(net.minecraft.class_1959@5354a59)

### BCLib

2.0.10

### Fabric API

0.57.0+1.19

### Fabric Loader

0.14.8

### Minecraft

1.19

### Other Mods

```shell
Terralith 2.3.1
```

**Comment by vedranskarica** [comment]
Tested with just BCLib, Fabric API and Terralith, no other mods.

**Comment by vedranskarica** [comment]
Testing further, if I create a world with Terralith but with BCLib removed, then add BCLib afterwards and restart, everything works fine. Also tested this sequence with a full modstack (terralith, BYG, biome makeover, better end, better nether, eden ring) and everything works fine if I first disable BClib (and betterX) when creating world, then enable them afterwards.

**Comment by quiqueck** [comment]
Hm, that was reported over at discord. But further testing showed that this isa problem with Terralith itself.

I just started a new World in a Minecraft Instance with only fabricate and Terralith installed. When I create a new world no Terralith Biomes are found 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/280847/178021741-fbfcc9db-2bd2-4920-b662-94ebe86d441d.png">

Leaving and reentering the world fixes the problem:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/280847/178022046-6c3b4497-c496-4c50-aa46-e7eff716fa2e.png">

In this test none of our mods were installed. Could you maybe confirm?

**Comment by vedranskarica** [comment]
weird, when I just put fabric API and terralith mod, I get normal biome generation on first run.
If I put fabric API + terralith + bclib I get no terralith biomes on first run, but on reload they do generate, same as you showed above
really strange, but I guess it's tied to the fabric issue.
I'll check again after fabric puts out another update.
thanks for answering quickly.
