### ISSUE TITLE
[Bug?] Permanent fog with Distant Horizons

### ISSUE THREAD

**Issue by shmove** [quiqueck/BCLib#203]
### What happened?

Using BCLib alongside Distant Horizons reveals a permanent fog that can't be removed by the Distant Horizons settings or additional mods like Sodium Extras.

### BCLib

21.0.13

### WorldWeaver

21.0.13

### Fabric API

0.102.0

### Fabric Loader

0.16.3

### Minecraft

1.21

### Other Mods

BetterEnd, Sodium, Lithium, Sodium Extras, Iris Shaders

**Comment by noahreinalter** [comment]
#185

**Comment by noahreinalter** [comment]
@shmove I didn't mean to say that it was fixed, it's just the same issue. I have the same issue with the same versions in a modpack I'm making

**Comment by shmove** [comment]
The linked reply mentions the existence of a config option, which I was unaware of. That option fixes my issue.
