### ISSUE TITLE
cannot load my world anymore or create a new one, most likely caused by BCLib https://bytebin.lucko.me/j5Wm2Zctxt

### ISSUE THREAD

**Issue by DeadDave59** [quiqueck/BCLib#21]
### What happened and how can i fix this?

i can no longer create a new world or load a world and it says the issue is caused by bclib, i've tried over ten times and restarted several times as well and it always says the same thing, all details are included in the crash report i've linked https://bytebin.lucko.me/j5Wm2Zctxt im running ultimate orgins 2.1 on curseforge, ive played for a long time without this issue and didnt make any changes, i just made a new world, played a bit, logged off and the next day i cant do anything all of a sudden 

### BCLib

v 1.4.6

### Minecraft

1.18.2

### Relevant log output

```shell
info in description and crash report https://bytebin.lucko.me/j5Wm2Zctxt
```

### Other Mods

```shell
info in description and crash report
```

**Comment by quiqueck** [comment]
Looks like the auto-fix system chokes on a corrupted/manually edited **level.dat** file in that world.

You can try if disabling the fixers helps. 

in **config/bclib/generator.json**:
Disable `fixEndBiomeSource` and `fixNetherBiomeSource`

in **config/bclib/main.json**:
Disable `applyPatches`

Make sure ou have a backup of your world before trying.

**Comment by Twisted-Code** [comment]
how does a corrupted/edited level.dat in one world prevent you from creating other worlds (as described in the initial issue)?
Asking because a friend is dealing with a similar issue and that part of your solution seemed odd to me, though we are trying it anyway...

**Comment by Twisted-Code** [comment]
She tried that solution (she streamed to discord as she edited the config) but still crashed. Here's a link to her crash report https://bytebin.lucko.me/akVQxGHXMJ
(Posting on her behalf because she doesn't have a github account)

**Comment by quiqueck** [comment]
Oh, I mostly looked at the crash-log and got that wrong. Sorry. 

But that is odd. The crash-log in the initial post is an error from our level-fixer. That code is not executed for new worlds. Are you sure that this log was from a fresh world?

The second one you posted is a different error. From the info I see there, I am not sure if it is a BCLib problem. Could you please post the regular log file as well. Might include more helpful information.
