### ISSUE TITLE
Add BCLib version 1.4.7 to the jitpack [Suggestion] 

### ISSUE THREAD

**Issue by LeMeowM** [quiqueck/BCLib#22]
### Description

As it is, BCLib-1.4.7 exists on the curseforge page, but is unable to be used for mod development as it just is nowhere to be found on jitpack, which as a 1.18.2 dev, forces me to use the older 1.4.6 version, which is not ideal.

Thanks!

**Comment by quiqueck** [comment]
Added it right now. 
You could also use `1.18.2-SNAPSHOT` as the version, but that would be slightly ahead of the public release.
