### ISSUE TITLE
Better X preset issue

### ISSUE THREAD

**Issue by CapJinbe** [quiqueck/BCLib#25]
When I try to create a world using the "Better X" preset, the world crashes. (when I use the "deafult" preset it works normally.)
[crash-2022-07-21_01.19.53-server.txt](https://github.com/quiqueck/BCLib/files/9156174/crash-2022-07-21_01.19.53-server.txt)

**Comment by CapJinbe** [comment]
Is there any way I can make the default world type "default" again, instead of "BetterX"? (I saw that in the "bclib" settings there is the option "forceBetterXPreset [default: true]"... I changed it to false but it remained the same.)

**Comment by CapJinbe** [comment]
is there any way I can make the default world type "default" again, instead of "BetterX"? (I saw that in the "bclib" settings there is the option "forceBetterXPreset [default: true]"... I changed it to false but it remained the same.)

**Comment by CapJinbe** [comment]
is there any way I can make the default world type "default" again, instead of "BetterX"? (I saw that in the "bclib" settings there is the option "forceBetterXPreset [default: true]"... I changed it to false but it remained the same.)

**Comment by quiqueck** [comment]
That setting is currently only for servers. Without the BetterX presets our mods will not work properly (some features will be missing)

**Comment by quiqueck** [comment]
Judging from the logs, the crash comes from `wythers:desert_river`-Biome and `byg:firecracker_shrubland`. Somehow features for both are added in an inconsistent order, which will crash the game.

**Comment by quiqueck** [comment]
Ok, I think I know why this only happens with the BetterX world type, and it is a _feature not a bug_. :)

From what I saw in my testing wwoo and bug are not compatible.

When you choose vanilla, you will simple not generate any Biomes from wwoo. BYG will take over the Overworld. That means the wythers biomes will never get initialised which in turn will not result in the inconsistent feature placement and the crash does not happen.

With BetterX you will still not get any Overworld-Biomes from wwoo (as we do not change the overworked behaviour). But we sort of run a sanity check, which surfaces that incompatibility.

**Comment by CapJinbe** [comment]
i will try to remove wwoo and create the world using Better X

**Comment by CapJinbe** [comment]
now the error is with terralith
[crash-2022-07-21_07.20.31-server.txt](https://github.com/quiqueck/BCLib/files/9158475/crash-2022-07-21_07.20.31-server.txt)

**Comment by CapJinbe** [comment]
can you explain how the "forceBetterXPreset [default: true]" option works?

**Comment by quiqueck** [comment]
That option should be a part of the server.json config. 

On a server, this will always enforce the BetterX-type (no matter what is configured in server.properties). If it is disabled, the world-type setting from the server.properties is honored.
