### ISSUE TITLE
[Bug] Mixin Confliction with TieredZ

### ISSUE THREAD

**Issue by itsdinkd** [quiqueck/BCLib#28]
### What happened?

As posted here; https://github.com/Globox1997/tiered/issues/11

"https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/common/AnvilMenuMixin.java#L180
BCLib overrides the onclick method (different mappings) so the tiered injection won't get used"

### BCLib

1.4.7

### Fabric API

fabric-api-0.57.0+1.18.2

### Fabric Loader

0.14.8

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Thanks for reporting. 

Are you sure this is the correct Mixin? I don't see any code on your end (presumably `AnvilScreenHandlerMixin`) that would conflict with that one. I do however see that we use the same override in `AnvilScreenMixin`:
https://github.com/Globox1997/tiered/blob/16f0d3430e4871badbb65782189a1842cf172fb9/src/main/java/draylar/tiered/mixin/client/AnvilScreenMixin.java#L62-L63
and ours
https://github.com/quiqueck/BCLib/blob/dcdaf4838d46905044624a73672edf6b5bbf741a/src/main/java/org/betterx/bclib/mixin/client/AnvilScreenMixin.java#L79-L80

**Comment by Globox1997** [comment]
first looked for errors in other repos, lul
not sure what happens if we both override the same method but since the class doesn't supply it we can't inject there

**Comment by quiqueck** [comment]
Well, the mixing that get's applied last will win and remove all earlier modifications. You should be able to force your implementation to the top by adding a priority>1000 to your mixing annotation.

**Comment by quiqueck** [comment]
Using Intrinsic Proxies instead of Override in 2.0.18

**Comment by oldjollysanta** [comment]
Any plans of applying these fixes to 1.18.2?

**Comment by quiqueck** [comment]
Yes, but there is no ETA as it currently has low priority.

As far as I can tell, TieredZ can just change the mixing priority to override ours. Which should be absolutely fine. Our mixing is there to show UI in case there are multiple recipes for the same list of ingredients. I think that is not uses in 1.18.2 anyway.
