### ISSUE TITLE
[Bug] Broken item recipies

### ISSUE THREAD

**Issue by Kris2031** [quiqueck/BCLib#29]
### What happened?

Broken item recipies. I am able to craft a bucket from nothing.

### BCLib

2.0.18

### Fabric API

0.58.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment]
Thanks for reporting. Will release a fixed version soon

**Comment by quiqueck** [comment]
Fixed in BCLib 2.0.19
