### ISSUE TITLE
[Bug] Guardian detected an incompatible World with Incendium

### ISSUE THREAD

**Issue by spoorn** [quiqueck/BCLib#3]
### What happened?

I always get this when trying to load into a single player with just Incendium and BCLib: 

![image](https://user-images.githubusercontent.com/12925899/173212643-44596ebd-3e6c-40cc-b1d5-44b799fbc268.png)

### BCLib

1.4.7

### Fabric API

0.55.1

### Fabric Loader

0.14.6

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Yes, this is a Bug with the way 1.18.2 handles Datapacks. Quick fix, is to turn off the level check in your configs.

Replace 
`"repairBiomesOnLoad [default: true]": true`
with
`"repairBiomesOnLoad [default: true]": false`

in `config/bclib/main.json`
