### ISSUE TITLE
[Suggestion] Update 1.18.2 to 2.0.x

### ISSUE THREAD

**Issue by Baxmann** [quiqueck/BCLib#32]
### Description

Please update the 1.18.2 version of the mod to the 2.0.x updates. [This bug](https://github.com/quiqueck/BetterEnd/issues/29) with BYG persists on 1.18.2, because there is no 2.0.11 for that version of the game.

**Comment by quiqueck** [comment]
2.x uses some enhancements in Minecraft 1.19 that help us to address those loader bugs from the 1.18.2 Version. We could need to back port those Minecraft changes to the 1.18.2 Version, which is a huge time investment. So this is probably not going to happen.
