### ISSUE TITLE
[Suggestion] Please enable a less verbose mode in config

### ISSUE THREAD

**Issue by purejosh** [quiqueck/BCLib#41]
### Description

The amount of log lines that come from bclib, every single server start and client login, are insanely high. I think an option to enable less verbose logging would be appreciated by server owners who are researching their log lines for issues. 

It would be different if these log lines were actually making changes, but there's so many lines that are repeating every single server boot, and they aren't modifying any files, just verbosely stating what they're doing. If we could enable a less verbose mode, we could agree to not receive support until we disable less verbose, as it could be hiding log lines that would be indicative of issues we're having. 

It would be appreciated. :) thanks!

**Comment by quiqueck** [comment]
Thanks for the suggestion :)

I disabled some of the logging I found. But please feel free to let me know if you have other log-lines in mind that I should include.

**Comment by purejosh** [comment]
Appreciate it! I have a server running 170+ mods now, would it be possible to reduce the logging for every mod offered to the client on login?

**Comment by quiqueck** [comment]
Ah, just saw that. I will add that for the next release :)

**Comment by purejosh** [comment]
Thank you so much, I really appreciate it! Would this also have anything to do with the lag spikes that other players experience when someone logs into the server? I always get a ~40ms "is the server running behind?" spike whenever someone logs in, which is also when the console shows the list of mods.

**Comment by quiqueck** [comment]
2.1.2 will disable the data exchange messages as well. However, the lag spike might also be from the fact that a lot of data is exchanged between client ad server. You might t want to consider to turn off the mod syncing all together if the issue persists for you.
