### ISSUE TITLE
[Bug] Datapacks disabled upon world rejoin

### ISSUE THREAD

**Issue by ZorkIsEmo** [quiqueck/BCLib#43]
### What happened?

create world and i can use /structure locate terralith: all fine, leave the game and reload in 1.19.2 and any strcuture from datapacks dont load anymore and the datapacks are considered unloaded? bug or feature? is there somthing im doing wrong?

### BCLib

2.1.0

### Fabric API

0.60.0

### Minecraft

1.19

### Other Mods

```shell
terralith datapack, oh the biomes youll go
```

**Comment by quiqueck** [comment]
Could you run the command `/bclib print dimensions` in the reloaded world and post a screenshot or the log-file (you can upload it directly to your reply). There should be a line **namespaces = minecraft, terralith** for the **minecraft:overworld**

If terrallith appears as one of the namespaces, then it is loaded properly. 

Could you also please attach a log file (after you did reload a world and run into the described problem). Without it, it is hard to help as I can not reproduce this behaviour in a testing world.
