### ISSUE TITLE
[BUG] (1.19 fabric version) ANVILS do not work for recipes

### ISSUE THREAD

**Issue by DESTRUCT10N** [quiqueck/BCLib#45]
### Description

the issue here is with the anvil, any anvil in survival mode , do not make any mod recipe, incompatibility, the recipes are unrecongizable in the game with the hammer or in the smithing table

**Comment by quiqueck** [comment]
Any of our Mods (BetterEnd) Recipes, or is there a problem with the recipes of other mods?

**Comment by DESTRUCT10N** [comment]
> Any of our Mods (BetterEnd) Recipes, or is there a problem with the recipes of other mods?

Yes, the better end mod, i use the EMI to view the recipes but when i'm playing the Game in survival mode the anvils of better end do not work properly i cannot craft the upgrated armors, it's bugged

**Comment by quiqueck** [comment]
Duplicate of quiqueck/BetterEnd#64
