### ISSUE TITLE
[Bug] Small end islands do not generate on quilt loader

### ISSUE THREAD

**Issue by dopadream** [quiqueck/BCLib#49]
### What happened?

Self explanatory, small end islands do not generate at all and cannot be located if the server is using quilt loader 

### BCLib

2.1.2

### Fabric API

Quilted 4.0.0

### Fabric Loader

0.17.5-beta.2

### Minecraft

1.19.2

### Relevant log output

```shell
nothing noteworthy related to the issue
```

### Other Mods

```shell
none
```

**Comment by quiqueck** [comment]
Small End Islands are a feature that can be turned off. Could you please attach the data/worlds_together.nbt file so I can have a look if our default World-Config on Quilt is wrong?
