### ISSUE TITLE
[Bug] Not possible to specify vanilla generator for un-modded dimension? 

### ISSUE THREAD

**Issue by OpenBagTwo** [quiqueck/BCLib#56]
### What happened?

When playing a Minecraft instance with only BetterEnd (and explicitly not BetterNether), the worldgen for _both_ Nether and End dimensions is set to BetterX. The primary consequence of this is that biomes, structures and other points of interest do not generate where predicted by tools such as [chunkbase](https://www.chunkbase.com/).

My expectation would be that _the default behavior_ would be that the Nether would stay completely untouched if BetterNether were not installed (and vice versa), but barring that, I would expect there to be a configuration option I could change to disable BetterX worldgen settings on a per-dimension basis, but even after explicitly setting:

- main.json
  - applyPatches: false,
  - repairBiomesOnLoad: false (already the default)
- server.json
  - auto_sync
    - forceBetterXPreset: false
- generator.json
  - options
    - biomeSource
      - fixNetherBiomeSource: false

and editing `level.dat` to reset the world gen settings for the Nether, when loading the world, logs show that BCLib "fixes" the Nether's worldgen to use the "correct generator, and opening up `level.dat` again confirms that the Nether world gen settings have reverted to BetterX

### BCLib

2.1.2

### Fabric API

0.63.0

### Fabric Loader

0.14.10

### Minecraft

1.19.2

### Relevant log output

```shell
[22:29:54] [Render thread/INFO]: [bclib] Loading from builtin Registry
[22:29:54] [Render thread/INFO]: [bclib] Running Pre Patchers on /home/openbagtwo/.minecraft/saves/Esha Ness/.
[22:29:54] [Render thread/INFO]: [DataFixerAPI] Everything up to date
[22:29:55] [Render thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[22:29:55] [Render thread/INFO]: [bclib] Loading from datapack Registry
[22:29:55] [Render thread/INFO]: [bclib] Enforcing Correct Generator for minecraft:the_nether.
```

### Other Mods

```shell
- BetterEnd 2.1.1
- sodium 0.4.4+build.18
- lithium 0.10.0
- lazydfu 0.1.3
```

**Comment by quiqueck** [comment]
You can change the settings per dimension in the World-Generator UI. Navigate to **Create New World** -> **More World Options ...** -> **Customise**, and turn off **Use Custom BiomeSource** for the Nether. That will deactivate our extension.
<img width="966" alt="CustomizeWorld" src="https://user-images.githubusercontent.com/280847/202002154-d7a22ba9-aace-47f0-947d-85c8c5edcd9e.png">

For an existing world, you need to edit the `data/worlds_together.nbt`file, not the `level.dat`. When that file is changed, bclib will automatically fix the `level.dat` file when you load the world.

**Comment by quiqueck** [comment]
I'll close this for now. If there are still issues/questions, please re-open the issue.
