### ISSUE TITLE
[Bug] Do not reverse scrolling on the welcome screen

### ISSUE THREAD

**Issue by Ampflower** [quiqueck/BCLib#57]
### What happened?

When attempting to scroll down with a mouse on the welcome screen, it scrolls *opposite* as to how you'd expect every other application to behave, including Minecraft.

Note, this was on Quilt, although the loader is most likely irrelevant here, as... why would that determine the scroll direction.

If this was an attempt to fix trackpad scrolling, try to poll the system where possible (either via Minecraft's own helpers or through system APIs) instead of assuming that everyone uses a touchpad the same way and affecting how the mouse scroll wheel works.

Note: On KDE Plasma, attempting to detect reverse scrolling seems to be entirely unneeded.

*If this was reported on the wrong repo, feel free to move this to the correct one.*

### BCLib

2.1.3

### Fabric API

Quilted Fabric API 4.0.0-beta.19+0.64.0-1.19.2

### Fabric Loader

Quilt Loader 0.18.1-beta.10

### Minecraft

1.19.2

### Other Mods

```shell
Note: Paired with BetterEnd.

The rest is most likely irrelevant here, but is provided for the sake of completeness.

- affectionate-1.1.2+1.19.jar
- appleskin-fabric-mc1.19-2.4.1.jar
- architecture_extensions-1.1.1+1.19.jar
- architectury-6.3.49-fabric.jar
- aurorasdecorations-1.0.0-beta.10+1.19.jar
- bclib-2.1.3.jar
- better-end-2.1.1.jar
- Botania-1.19.2-436-FABRIC-SNAPSHOT.jar
- cloth-config-8.2.88-fabric.jar
- create-fabric-1.19.2-0.5.0f-764.jar
- ears-fabric-1.19-1.4.6.jar
- extraorigins-1.19-2.jar
- fabric-carpet-1.19.2-1.4.84+v221018.jar
- fabrictailor-2.0.1.jar
- ferritecore-5.0.0-fabric.jar
- immersive_armors-1.4.2.jar
- inspecio-1.6.0+1.19.jar
- inventorymanagement-1.1.0+1.19.jar
- lambdynamiclights-2.1.2+1.19.jar
- lazydfu-0.1.3.jar
- modmenu-4.1.0.jar
- Origins-1.19.2-1.7.1.jar
- Origins-Classes-1.19-1.4.0.jar
- Patchouli-1.19.2-77-FABRIC.jar
- Pehkui-3.6.0+1.14.4-1.19.3.jar
- polymorph-fabric-0.45.0+1.19.2.jar
- quilted-fabric-api-4.0.0-beta.19+0.64.0-1.19.2.jar
- raknetify-fabric-0.1.0+alpha.5.15-all.jar
- starlight-1.1.1+fabric.ae22326.jar
- trinkets-3.4.0.jar
- voicechat-quilt-1.19.2-2.3.13.jar
```

**Comment by quiqueck** [comment]
BCLib does nothing of the sort. We just read the values from the Minecraft API. On our side, there is no attempt to detect reverse scrolling.
