### ISSUE TITLE
BCLib not spawning nullscape biomes in game

### ISSUE THREAD

**Issue by Darth-Bellic** [quiqueck/BCLib#70]
### What happened?

after hours of searching for nullscape biomes while used in tandem with BCLib and better end i could find no NS biomes, after a brief chat with one of the stardust labs dev team (tera to be specific) they stated its a BCLib issue, i saw there was no issue here mentioning this so i thought id write a bug report up here.

Its worth noting that while none of nullscape's biomes spawn, its modified terrain gen does seem to work fine albiet causing slight gen wierdness that may not be intended, like rainbow crystals being about 3x as tall as they usually are

### BCLib

2.2.3

### Fabric API

0.72.0

### Fabric Loader

0.14.12

### Minecraft

1.19.3

**Comment by quiqueck** [comment]
Does your world use the BCLib Worldtypes or the regular ones?

**Comment by quiqueck** [comment]
Oh, and did you use the nulls cape datapack or mod?
