### ISSUE TITLE
[Suggestion] BetterX & Large world preset for a server

### ISSUE THREAD

**Issue by PlazmaKG** [quiqueck/BCLib#71]
### Description

I wish to have large biomes, but with the BetterX world generation preset as well. When generating a single player world, There is a preset called "Large & BetterX" which is what I'm after, but I can't figure out how to use that on a server since I don't know what to put for "level-type" in server.properties. I've looked in many places on the internet and can't seem to find a solution anywhere. Would you guys be able to provide what it is to me?

As for why I put this as a suggestion, you should put this information in a place where it's easy to find since I had a lot of trouble trying to.
Thanks :)

Using Minecraft 1.19.2

**Comment by quiqueck** [comment]
For a server, you need to put that in your `server.properties`-File (before you generate the world).

In specific you need to add/change the following:
```ini
level-type=bclib\:large
```
