### ISSUE TITLE
[Suggestion] Add back the emissive texture stuff

### ISSUE THREAD

**Issue by oliviathevampire** [quiqueck/BCLib#73]
### Description

The old BCLib used to have some shaders + code to allow for emissive textures, I would love to have this again

**Comment by paulevsGitch** [comment]
This was important part of BCLib, I hope it was just not ported to 1.19.3 yet

**Comment by quiqueck** [comment]
I'll have to check how 1.19.4 is doing in that department. Once the Resource-handling stuff is stable, I'll add it back.
