### ISSUE TITLE
[Suggestion] Remove the `Tried to read from global registry!` error log messages from Worlds Together.

### ISSUE THREAD

**Issue by surge541** [quiqueck/BCLib#90]
### Description

I get that this is it's intended purpose - to warn the player about something that shouldn't of happened, but it creates immensely large log files, as well as making it impossible to actually read any useful messages. 

I'm proposing that this message is removed, or toggleable in a config. Alternatively, it could just be logged once, but not spammed.

Thanks in advance.

**Comment by quiqueck** [comment]
Released with BetterEnd 3.1.3/3.2.1 (if you turn off verbose logging). If it does not fix the issue, please re-open.
