### ISSUE TITLE
Crashing when adding eden ring and on the biomes you'll go to world

### ISSUE THREAD

**Issue by SuccBT** [quiqueck/BCLib#95]
### What happened?

Whenever I try and put oh the biomes you'll go or eden ring onto a world that was made before i put these mods on with bclib the game will pull up the "Guardian detected an incompatible world" screen and tell me to apply fixes. Once progress gets to 100 the game will try to load the world and then crash.

### BCLib

2.1.6

### Fabric API

0.7.6.0

### Fabric Loader

0.14.19

### Minecraft

1.19.4

### Relevant log output

```shell
https://pastebin.com/9uynrvQt
```

### Other Mods

```shell
https://imgur.com/a/0ctt8YQ
```

**Comment by quiqueck** [comment]
Did you already report this on the EdenRing Issue Tracker (https://github.com/paulevsGitch/EdenRing/issues)? I do not see anything specific to BCLib in the crashlog...
