### ISSUE TITLE
[Bug] Client crash with EMI 1.0.0

### ISSUE THREAD

**Issue by lxly9** [quiqueck/BCLib#96]
### What happened?

When clicking 'View all recipes' in EMI's recipe tab the game crashes. It's caused by EMIAnvilRecipeCategory but only appears when BCLib and any BetterX mods are installed. 

### BCLib

2.1.6

### Minecraft

1.19.2

### Relevant log output

```shell
https://mclo.gs/65cxXxq
```

### Other Mods

```shell
EMI 1.0.0
```

**Comment by lxly9** [comment]
Ive created forks of the [betterx mods](https://modrinth.com/mod/betterx-jemi). I recommend using these until BetterX plugins get updated.

**Comment by quiqueck** [comment]
Sound be fixed in 2.1.7
